# Standards: 0.1
---
- name: Kill iterm2
  command: killall iTerm
  register: iterm_kill
  failed_when: iterm_kill.rc != 0 and "No matching processes belonging to you were found" not in iterm_kill.stderr
  become: "{{ (iterm_user != ansible_user_id) | bool }}"
  become_user: "{{ iterm_user }}"

- name: Start iterm2
  when: iterm_started
  command: open -g /Applications/iTerm.app
  become: "{{ (iterm_user != ansible_user_id) | bool }}"
  become_user: "{{ iterm_user }}"

...
